# Generated by Django 4.2.1 on 2023-05-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('students', '0004_alter_student_email_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
